### ISSUE TITLE
Configure call across containers in a docker stack not establishing provided topology, only default response

### ISSUE THREAD

**Issue by rhyslbw** [arobson/rabbot#108]
I have a service that uses the `configure` api to connect to a container running an extended version of rabbitmq:3.6.12-management in the stack via the default network. The extension wraps the entrypoint to setup some users. Only the default response topology is created after the connection is establishd when bringing the stack up with docker-compose. The `default.connection.configured` event is never fired, and the connection seems to be getting closed in the broker container.

```
** accepting AMQP connection <0.613.0> (172.18.0.4:33004 -> 172.18.0.3:5672) **
[rabbot.topology] Declaring undefined exchange '' on connection 'default' with the options: {"passive":true}
[rabbot.queue] Starting subscription to queue '6bbeccc16f74.node.6.response.queue' on 'default'
[rabbot.queue] Subscription to (tracked) queue 6bbeccc16f74.node.6.response.queue - default started with consumer tag 6bbeccc16f74.node.6.response.queue
** closing AMQP connection <0.577.0> (172.18.0.4:33000 -> 172.18.0.3:5672) **
```

When I run the service separately outside of the stack it connects and works as expected. I'll put together a reproduction, but wanted to raise the issue first incase there's anyone else experiencing the same problem who can shed some light on this.

**Comment by rhyslbw** [comment]
https://github.com/rhyslbw/rabbot-configure-docker

**Comment by edorsey** [comment]
I ran into this same problem as well. It appears that this module makes an assumption: 

> RabbitMQ will be running when rabbot tries to connect.

This is not the case with docker-compose.

To fix this, I did two things, after getting the `connected` event from `rabbot`. It is a bit hacky, but it appears to work:

```
let rabbit = require("rabbot")

let connection = {
  //connection details
};

rabbit.addConnection(connection) //Start by adding the connection only

rabbit.on("connected", function(a, b) {
  //Once we've connected, replace the connection promise with one that automatically resolves
  //Prior to this change, this is the original promise that failed. Publishing will always fail because of this.
  rabbit.connections["rabbitmq"].promise = new Promise(function (resolve, reject) {
    resolve()
  })

  //Now reconfigure rabbit because if it fails its initial connection, the configuration doesn't ever get setup
  rabbit.configure({
    connection: connection,
    exchanges: [],
    queues: [],
    bindings:[]
  })
})
```

Not 100% that using the built-in `Promise` will cause any issues with the promises used in this project.

**Comment by antmarot** [comment]
I had the same issue.

It is true that more attempts to connect will be made but the promise returned by `configure` is rejecting on the first failed attempt.

I ended up doing this
```javascript
function connect() {
  return rabbot.configure({
    connection: {
      /* connection details */
      retryLimit: 0, // no implicit retries
    },
    /* other options */
  }); 
}

async function connectWithRetry(attempts = 1) {
  try {
    await init();
  } catch (err) {
    if (attempts < 5) {
      console.log('Connection to RabbitMQ failed. Retrying in 5s...');
      await Promise.delay(5000);
      return connectWithRetry(attempts + 1);
    }
    throw err;
  }
}
```

**Comment by genemyers** [comment]
@antmarot When I tried your code I received a UnhandledPromiseRejectionWarning when the connection is unreachable and the code exits. There's not a catch block on the configure promise, but I've had little luck adding one and making this work. Any insight would be appreciated.

**Comment by antmarot** [comment]
@genemyers I added a snippet calling the connection logic. Hope this helps.

**Comment by genemyers** [comment]
@antmarot would you be so kind as to provide a single module that demonstrates your solution? 
When I try and run this example:
```
const Rabbot = require("rabbot");

 async function connect() {
  await rabbot.configure({
    connection: {
      /* connection details */
      uri:"amqp://test-rabbitmq",
      retryLimit: 0, // no implicit retries
    },
    /* other options */
  });

  // Update internal promise - see @edorsey code
  const connectionName = 'default';
  rabbot.connections[connectionName].promise = Promise.resolve();
}

async function connectWithRetry(attempts = 1) {
  try {
    await connect();
  } catch (err) {
    if (attempts < 5) {
      console.log('Connection to RabbitMQ failed. Retrying in 5s...');
      await Promise.delay(5000);
      return connectWithRetry(attempts + 1);
    }
    throw err;
  }
}

async function connectRabbit() {
  try {
    await connectWithRetry();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

connectRabbit();
```
 now I now get this error:
```
$docker-compose up
Creating network "rabbitmq_test-net" with driver "bridge"
Creating test-rabbitmq  ... done
Creating test-rabbit-01 ... done
Creating test-rabbit-01 ... done
Attaching to test-rabbitmq, test-rabbit-01
test-rabbit-01    |
test-rabbit-01    | > rabbit-01@0.0.1 start /usr/src/app

test-rabbit-01    | > node server.js
test-rabbit-01    |
test-rabbit-01    | Connection to RabbitMQ failed. Retrying in 5s...
test-rabbit-01    | TypeError: Promise.delay is not a function
test-rabbit-01    |     at connectWithRetry (/usr/src/app/server.js:68:21)
test-rabbit-01    |     at process._tickCallback (internal/process/next_tick.js:178:7)
test-rabbit-01    |     at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
test-rabbit-01    |     at startup (internal/bootstrap/node.js:228:19)
test-rabbit-01    |     at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
test-rabbit-01    | npm ERR! code ELIFECYCLE
test-rabbit-01    | npm ERR! errno 1
test-rabbit-01    | npm ERR! rabbit-01@0.0.1 start: `node server.js`
test-rabbit-01    | npm ERR! Exit status 1
test-rabbit-01    | npm ERR!
test-rabbit-01    | npm ERR! Failed at the rabbit-01@0.0.1 start script.
test-rabbit-01    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
test-rabbit-01    |
test-rabbit-01    | npm ERR! A complete log of this run can be found in:
test-rabbit-01    | npm ERR!     /root/.npm/_logs/2018-12-03T11_51_32_844Z-debug.log
test-rabbit-01 exited with code 1
```

**Comment by antmarot** [comment]
@genemyers I now included the module dependencies. `Promise.delay` is provided by `bluebird`.

**Comment by genemyers** [comment]
@antmarot Doh! I should have caught that, thanks.

**Comment by genemyers** [comment]
@antmarot Thank you, all working now.
