### ISSUE TITLE
rabbot.shutdown() error on NodeJS 10.0.0

### ISSUE THREAD

**Issue by nhanle92** [arobson/rabbot#156]
Error only occurs when run with babel

When switch to Node version 10.0.0 the library return errors when `rabbot.shutdown()` called. Tested with manually call the `rabbot.closeAll()`

Worked fine on NodeJS 9

> 2018-05-03T14:56:14.703+07:00 error [rabbot.io]: Error emitted by connection 'default' - 'TypeError: reply is not a function
>     at Channel.C.accept (/Users/nhanle/test-project/node_modules/amqplib/lib/channel.js:433:12)
>     at Connection.mainAccept [as accept] (/Users/nhanle/test-project/node_modules/amqplib/lib/connection.js:64:33)
>     at Socket.go (/Users/nhanle/test-project/node_modules/amqplib/lib/connection.js:477:48)
>     at Socket.emit (events.js:182:13)
>     at Socket.EventEmitter.emit (domain.js:442:20)
>     at emitReadable_ (_stream_readable.js:540:12)
>     at process._tickCallback (internal/process/next_tick.js:174:19)'
> internal/util.js:360
>     const filename = frame.getFileName();
>                            ^
> 
> TypeError: frame.getFileName is not a function
>     at isInsideNodeModules (internal/util.js:360:28)
>     at showFlaggedDeprecation (buffer.js:149:8)
>     at new Buffer (buffer.js:174:3)
>     at Array.<anonymous> (/Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:149:21)
>     at /Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:53:24
>     at mapSourcePosition (/Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:171:21)
>     at wrapCallSite (/Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:343:20)
>     at /Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:378:26
>     at Array.map (<anonymous>)
>     at Function.prepareStackTrace (/Users/nhanle/test-project/node_modules/source-map-support/source-map-support.js:377:24)
>     at CapturedTrace.attachExtraTrace (/Users/nhanle/test-project/node_modules/bluebird/js/release/debuggability.js:784:38)
>     at Promise.longStackTracesAttachExtraTrace [as _attachExtraTrace] (/Users/nhanle/test-project/node_modules/bluebird/js/release/debuggability.js:410:19)
>     at /Users/nhanle/test-project/node_modules/bluebird/js/release/nodeback.js:39:21
>     at reply (/Users/nhanle/test-project/node_modules/amqplib/lib/channel.js:116:43)
>     at rej (/Users/nhanle/test-project/node_modules/amqplib/lib/channel.js:190:5)
>     at Channel.C._rejectPending (/Users/nhanle/test-project/node_modules/amqplib/lib/channel.js:192:28)

**Comment by nhanle92** [comment]
It seems there are problems with the new NodeJS and V8 engine.

**Comment by nhanle92** [comment]
Never mind. The problem caused by babel-node because of its sourcemaps.

I have to debug my app using the compiled file, not run the app via babel-node.
