### ISSUE TITLE
Error thrown on unexpected disconnect

### ISSUE THREAD

**Issue by droidenator** [arobson/rabbot#3]
If a worker loses it's connection unexpectedly, the following error is thrown. I'm currently using Rabbot version 1.0.0-2. I'm running RabbitMQ 3.5.6 on OS X. 

```
Potentially unhandled rejection [3] TypeError: this._onFailure is not a function

    at null.<anonymous> (/work/microservices/node_modules/rabbot/src/queueFsm.js:150:13)

    at Object.invokeSubscriber (/work/microservices/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:182:19)

    at invoker (/work/microservices/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:430:11)

    at /work/microservices/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:324:5

    at arrayEach (/work/microservices/node_modules/rabbot/node_modules/lodash/index.js:1289:13)

    at Function.<anonymous> (/work/microservices/node_modules/rabbot/node_modules/lodash/index.js:3345:13)

    at /work/microservices/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:436:7

    at /work/microservices/node_modules/rabbot/node_modules/lodash/index.js:3073:15

    at baseForOwn (/work/microservices/node_modules/rabbot/node_modules/lodash/index.js:2046:14)

    at /work/microservices/node_modules/rabbot/node_modules/lodash/index.js:3043:18```

**Comment by derickbailey** [comment]
I'm seeing the same error when my connection gets dropped

```
TypeError: this._onFailure is not a function
     at null.<anonymous> (/Users/derickbailey/dev/projects/rabbus/node_modules/rabbot/src/queueFsm.js:150:13)
     at Object.invokeSubscriber (/Users/derickbailey/dev/projects/rabbus/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:182:19)
 ...
```

**Comment by arobson** [comment]
@droidenator @derickbailey - we ran into this as well. We're up to pre-lease 7 in NPM right now which should have resolved this. Let me know if you're still seeing it.

**Comment by derickbailey** [comment]
ok, cool. i haven't had time to try the latest updates in a while. will see if i can make time for this, soon

**Comment by arobson** [comment]
@droidenator @derickbailey going to close this one, it should be resolved (we've not seen it since the fix was put in). Let me know if you're still getting it on 1.0.0-8 or later.
