### ISSUE TITLE
Why does rabbot try to establish topology even before the connection is acquired?

### ISSUE THREAD

**Issue by alex-shnayder** [arobson/rabbot#32]
The following code:

```javascript
var rabbot = require('rabbot');

rabbot.configure({
  connection: {
    retryLimit: 3
  },
  exchanges: [{
    name: 'test',
  }],
  logging: {
    adapters: {
      stdOut: {
        level: 1
      }
    }
  }
});
```

Produces this output:
```
2016-08-02T05:29:11.144Z [rabbot.io] Acquisition of connection 'default' failed with 'No endpoints could be reached'
2016-08-02T05:29:11.155Z [rabbot.topology] Failed to create reply queue for connection name 'default Error: Failed to create queue 'cfc395df9998.node.5.response.queue' on connection 'default' with 'No endpoints could be reached'
    at .<anonymous> (/root/app/node_modules/rabbot/src/topology.js:195:10)
    at onConnectionFailed (/root/app/node_modules/rabbot/src/topology.js:207:13)
    at /root/app/node_modules/rabbot/src/topology.js:213:6
    at Object.invokeSubscriber (/root/app/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (/root/app/node_modules/monologue.js/lib/monologue.js:430:11)
    at /root/app/node_modules/monologue.js/lib/monologue.js:324:5
    at arrayEach (/root/app/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/root/app/node_modules/lodash/index.js:3345:13)
    at /root/app/node_modules/monologue.js/lib/monologue.js:436:7
    at /root/app/node_modules/lodash/index.js:3073:15
Potentially unhandled rejection [4] No endpoints could be reached (WARNING: non-Error used)
2016-08-02T05:29:11.163Z [rabbot.io] Acquisition of connection 'default' failed with 'No endpoints could be reached'
2016-08-02T05:29:11.266Z [rabbot.io] Acquisition of connection 'default' failed with 'No endpoints could be reached'
```

Maybe I'm missing something, but I wouldn't expect the "Failed to create reply queue" error to appear because why even try to create a queue when not connected? Seems pretty futile to me.

**Comment by arobson** [comment]
@alex-shnayder - rabbot makes certain calls (and allows you to) regardless of when the connection is established. In most cases the call being made sets up state machines responsible for reacting to events so that when the connection is established everything resolves.

The assumption is that if the connection isn't available yet, it will be soon. And if it isn't going to be within the configured tolerance, it will raise the `unreachable
