### ISSUE TITLE
error defining topology: "queue" is not defined on "this.queue.define()" call

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#38]
every now and then - for reasons i don't yet understand - i get an error that looks like it is coming from an attempt to define topology in my app.

i don't yet know what code is causing this to run or causing the error as i haven't been able to track it down, yet.

but i wanted to drop this error message in here to see if anyone else has run into the problem or might have a good idea on how to debug this.

here is the error message, pointing at [this line of code in the queueFSM](https://github.com/arobson/rabbot/blob/master/src/queueFsm.js#L40).

```
Potentially unhandled rejection [3] TypeError: Cannot read property 'define' of undefined
    at machina.Fsm.extend._define (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/src/queueFsm.js:40:14)
    at null.<anonymous> (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/src/queueFsm.js:46:11)
    at Object.invokeSubscriber (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:430:11)
    at arrayEach (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/lodash/index.js:3345:13)
    at Monologue.emit (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:439:6)
    at machina.Fsm.extend.states.acquired._onEnter (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/src/amqp/iomonad.js:196:11)
    at _.extend.transition (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/machina/lib/machina.js:433:27)
    at Fsm.(anonymous function) [as transition] (/Users/derickbailey/dev/scott-white/scheduler/node_modules/rabbot/node_modules/machina/lib/machina.js:580:60)
```

This error does not occur at a specific time or point in my code, and I cannot yet reproduce it on command.

If I had to guess, I would wonder if there's a problem with RabbitMQ connection or channel being dropped and attempts to reconnect and reestablish the topology is failing.

But again, I'm not sure what's going on. It doesn't happen at any regular time or interval - i have not been able to track it down yet, but it is causing me major problems right now.

**Comment by derickbailey** [comment]
i can confirm this is due to re-building the topology on connection / channel drop. i'm not 100% certain on the specifics of a basic reproduction example, yet. working on that next.

**Comment by ecasilla** [comment]
+1

**Comment by derickbailey** [comment]
finally got this isolated to message consumers. i've put together code that reproduces the scenario on demand.

https://gist.github.com/derickbailey/dd1473170ec3149a237bf242ed6e5860

in this gist, there are 2 files. 

run `node sender.js` to create a queue and put a message into it

then run `node debug receiver.js` to receive the message, with debugger attached. 

when the debugger starts, hit `c` to continue and consume the message. a second later, the `debugger` statement on line 24 will hit. 

when the debugger statement breaks, DO NOTHING.

let the debugger hang there, and go do something else for a few minutes.

eventually, the connection to RabbitMQ will die.

after the connection to rabbitmq dies, for the sender.js process, hit `c` in the debugger again, to continue.

you will immediately get the error message, as shown above, when Rabbot tries to rebuild the connection and topology.

```
 TypeError: Cannot read property 'define' of undefined
     at machina.Fsm.extend._define (/Users/derickbailey/dev/test/rabbottest/node_modules/rabbot/src/queueFsm.js:40:14)
```

**Comment by arobson** [comment]
@derickbailey - thanks for all the prep work on this. Really helps to have something I can use in creating a small test case. I've done another pretty hefty overhaul on the Queue FSM, this pass was to ditch the use of `queue` as a property so I could hopefully eliminate the race conditions. I _think_ I've managed to eliminate the race condition and I'm doing a little clean up and trying to see if there's any indications that I've missed cleaning up event handlers that would cause memory leaks before I push this.
