### ISSUE TITLE
Cannot invoke operation 'ack' on released channel

### ISSUE THREAD

**Issue by Cyri-L** [arobson/rabbot#41]
Hi, just faced this error: 

``` js
Error: Cannot invoke operation 'ack' on released channel 'queue:q.requests-abc'
    at machina.Fsm.extend.states.released.operate (/Users/Cyril/Projects/rockfox-lib/rabbot/src/amqp/iomonad.js:338:19)
    at _.extend.handle (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/machina/lib/machina.js:613:25)
    at Fsm.(anonymous function) [as handle] (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/machina/lib/machina.js:466:63)
    at machina.Fsm.extend.operate (/Users/Cyril/Projects/rockfox-lib/rabbot/src/amqp/iomonad.js:157:9)
    at .<anonymous> (/Users/Cyril/Projects/rockfox-lib/rabbot/src/amqp/iomonad.js:356:20)
    at .resolver (/Users/Cyril/Projects/rockfox-lib/rabbot/src/amqp/queue.js:227:20)
    at AckBatch._resolveAll (/Users/Cyril/Projects/rockfox-lib/rabbot/src/ackBatch.js:129:8)
    at AckBatch._processBatch (/Users/Cyril/Projects/rockfox-lib/rabbot/src/ackBatch.js:92:9)
    at .<anonymous> (/Users/Cyril/Projects/rockfox-lib/rabbot/src/ackBatch.js:228:9)
    at Object.invokeSubscriber (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/postal/lib/postal.js:171:19)
    at /Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/postal/lib/postal.js:541:17
    at arrayEach (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/lodash/lodash.js:9011:14)
    at Object.publish (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/postal/lib/postal.js:540:6)
    at ChannelDefinition.publish (/Users/Cyril/Projects/rockfox-lib/rabbot/node_modules/postal/lib/postal.js:76:11)
    at Timeout.Broker.batchAck [as _repeat] (/Users/Cyril/Projects/rockfox-lib/rabbot/src/index.js:153:9)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) undefined undefined
```

For now I decided to mute it by altering the portion of code : 

``` js
AckBatch.prototype._resolveAll = function( status, first, last ) {
    var count = this.messages.length;
    var emitEmpty = function() {
        process.nextTick( function() {
            this.emit( "empty" );
        }.bind( this ) );
    }.bind( this );
    if ( this.messages.length !== 0 ) {
        var lastTag = this._lastByStatus( status ).tag;
        log.debug( "%s ALL (%d) tags on %s - %s.",
            status,
            this.messages.length,
            this.name,
            this.connectionName );
        this.resolver( status, { tag: lastTag, inclusive: true } )
            .then( function() {
                this[ last ] = lastTag;
                this._removeByStatus( status );
                this[ first ] = undefined;
                if ( count > 0 && this.messages.length === 0 ) {
                    log.debug( "No pending tags remaining on queue %s - %s", this.name, this.connectionName );
                    // The following setTimeout is the only thing between an insideous heisenbug and your sanity:
                    // The promise for ack/nack will resolve on the channel before the server has processed it.
                    // Without the setTimeout, if there is a pending cleanup/shutdown on the channel from the queueFsm,
                    // the channel close will complete and cause the server to ignore the outstanding ack/nack command.
                    // I lost HOURS on this because doing things that slow down the processing of the close cause
                    // the bug to disappear.
                    // Hackfully yours,
                    // Alex
                    emitEmpty();
                }
                this.acking = false;


            }.bind( this )).catch(function(err){ **//MUTING**
                log.error( "An exception occurred while trying to resolve ALL ack/nack on %s - %s: %s", this.name, this.connectionName, err.stack );
            }.bind( this ));
    }
};

```

But do you have any idea where it's coming from ?

Thank you !

**Comment by derickbailey** [comment]
from a general perspective, this error means the rabbitmq channel on which the message was received, has already been released (closed) before you are calling `ack` on the message.

do you have some code that can reproduce this problem, easily? can't really debug the issue without seeing it reproduced.

**Comment by arobson** [comment]
Closing this for now unless it continues to come up. I'm hopeful that bug fixes related to how rabbot cleans up have eliminated or reduced this edge case. I know you put a lot of effort at one point into trying to eliminate the issue but I couldn't merge those changes in without test coverage.
