### ISSUE TITLE
can't get simple demo code to work

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#5]
I'm trying to put together a simple demo to track down my other issue in #4, but i can't get even a simple demo to work. I constantly run into `No endpoints could be reached` errors.

This is my code:

```js
var rabbot = require("rabbot");

var config = {
  connection: {
    host: "localhost",
    user: "test",
    pass: "test",
    vhost: "/wascally-demo"
  },

  exchanges: [{ name: "rabbot.ex.1", type: "direct" }],

  queues: [{ name: "rabbot.q.1", subscribe: false }],

  bindings: [{ exchange: "rabbot.ex.1", target: "rabbot.q.1", keys: "some.key" }]
};

rabbot.configure(config)
  .then(function(){
    receive();
  })
  .then(undefined, reportError);

function receive(){
  rabbot.handle("some.type", function(msg){
    msg.ack();
  });
  rabbot.startSubscription("rabbot.q.1");
}

function reportError(err){
  console.log(err.stack);
  process.exit();
}
```

the host, vhost, user and pass are correct. but when i try to run this code, i get:

```
Error: Failed to create exchange 'rabbot.ex.1' on connection 'default' with 'No endpoints could be reached'
    at null.<anonymous> (/Users/derickbailey/dev/test/node_modules/rabbot/src/topology.js:165:10)
    at onConnectionFailed (/Users/derickbailey/dev/test/node_modules/rabbot/src/topology.js:177:13)
    at /Users/derickbailey/dev/test/node_modules/rabbot/src/topology.js:183:6
    at Object.invokeSubscriber (/Users/derickbailey/dev/test/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:182:19)
    at invoker (/Users/derickbailey/dev/test/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:430:11)
    at /Users/derickbailey/dev/test/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:324:5
    at arrayEach (/Users/derickbailey/dev/test/node_modules/rabbot/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/derickbailey/dev/test/node_modules/rabbot/node_modules/lodash/index.js:3345:13)
    at /Users/derickbailey/dev/test/node_modules/rabbot/node_modules/monologue.js/lib/monologue.js:436:7
    at /Users/derickbailey/dev/test/node_modules/rabbot/node_modules/lodash/index.js:3073:15
```

**Comment by derickbailey** [comment]
ignore this... rabbitmq seems to not like a user with a name `test` ... any other name seems to work, though. *shrugs*
