### ISSUE TITLE
Crash because of `Unhandled 'error' event` 

### ISSUE THREAD

**Issue by TinOo512** [arobson/rabbot#71]
Hi, it seems that the `error` event which is emitted before the `close` event by the amqp [connection](https://github.com/squaremo/amqp.node/blob/93de8d1da76883d670e7f52855a697f1be610ea8/lib/connection.js#L426) isn't handled by [rabbot](https://github.com/arobson/rabbot/blob/master/src/connectionFsm.js#L188).

Because amqp use `events` when there is no handler listening for an event it [throw the error](https://github.com/Gozala/events/blob/master/events.js#L59).

The callstack : 
```
Jan 24 00:27:19:  Reconnecting broker attempt 9 failed, ... 
Jan 24 00:27:19:            Will wait 256000 ms before trying again. 
Jan 24 00:27:19:            error: Failed to create exchange 'default-ex' on connection 'default' with 'No endpoints could be reached' 
Jan 24 00:27:20:  2017-01-24T08:27:20.034Z [rabbot.connection] Attempting connection to 'default' (amqp://...?heartbeat=30) 
Jan 24 00:27:33:  2017-01-24T08:27:33.051Z [rabbot.connection] Failed to connect to 'default' (amqp://...?heartbeat=30) with, 'Error: connect ETIMEDOUT' 
Jan 24 00:27:33:  2017-01-24T08:27:33.052Z [rabbot.connection] Cannot connect to `default` - all endpoints failed 
Jan 24 00:27:33:  2017-01-24T08:27:33.052Z [rabbot.io] Acquisition of connection 'default' failed with 'No endpoints could be reached' 
Jan 24 00:27:35:  2017-01-24T08:27:34.970Z [rabbot.connection] Attempting connection to 'default' (amqp://...?heartbeat=30) 
Jan 24 00:27:45:  2017-01-24T08:27:44.982Z [rabbot.connection] Failed to connect to 'default' (amqp://...?heartbeat=30) with, 'Error: connect ETIMEDOUT' 
Jan 24 00:27:45:  2017-01-24T08:27:44.982Z [rabbot.connection] Cannot connect to `default` - all endpoints failed 
Jan 24 00:27:45:  2017-01-24T08:27:44.983Z [rabbot.io] Acquisition of connection 'default' failed with 'No endpoints could be reached' 
Jan 24 00:27:45:  Broker is unreachable, ... 
Jan 24 00:30:34:  events.js:160 
Jan 24 00:30:34:        throw er; // Unhandled 'error' event 
Jan 24 00:30:34:        ^ 
Jan 24 00:30:34:  Error: Heartbeat timeout 
Jan 24 00:30:34:      at Heart.<anonymous> (/app/node_modules/amqplib/lib/connection.js:425:19) 
Jan 24 00:30:34:      at emitNone (events.js:86:13) 
Jan 24 00:30:34:      at Heart.emit (events.js:185:7) 
Jan 24 00:30:34:      at Heart.runHeartbeat (/app/node_modules/amqplib/lib/heartbeat.js:88:17) 
Jan 24 00:30:34:      at Timeout.wrapper [as _onTimeout] (timers.js:417:11) 
Jan 24 00:30:34:      at tryOnTimeout (timers.js:224:11) 
Jan 24 00:30:34:      at Timer.listOnTimeout (timers.js:198:5) 
```

**Comment by arobson** [comment]
@TinOo512 - I think you're right about the cause, but I'm uncertain how to fix it. I attempted fixing it by changing the way the error event listener is attached in version `1.1.0`. Let me know if this appears to have resolved what you're seeing and re-open the issue if it didn't.
